---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lagopusvolume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/lagopusvolume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: myvol
spec:
 storageClassName: manual
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fuzztest
spec:
  activeDeadlineSeconds: 60
  parallelism: 5
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: myvol
      containers:
      - name: fuzztest
        image: qlyoung/lagopus-fuzzer:latest
        imagePullPolicy: Always
        args: ["afl", "2"]
        resources:
          requests:
            memory: "200Mi"
            cpu: "2"
          limits:
            memory: "200Mi"
            cpu: "2"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LAGOPUS_JOB_ID
          value: job-20
        volumeMounts:
          - mountPath: /jobdata
            name: test-volume
