apiVersion: batch/v1
kind: Job
metadata:
  name: fuzztest
spec:
  activeDeadlineSeconds: 240
  parallelism: 5
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: myvol
      containers:
      - name: fuzztest
        image: qlyoung/lagopus-fuzzer:latest
        imagePullPolicy: Always
        args: ["libfuzzer", "4"]
        resources:
          requests:
            memory: "200Mi"
            cpu: "4"
          limits:
            memory: "200Mi"
            cpu: "4"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LAGOPUS_JOB_ID
          value: job-20
        volumeMounts:
          - mountPath: /jobdata
            name: test-volume
