apiVersion: v1    
kind: PersistentVolumeClaim    
metadata:    
 name: jobdata-pvc
spec:    
 storageClassName: manual    
 accessModes:    
   - ReadWriteMany
 resources:    
   requests:    
     storage: 1Gi  
