apiVersion: v1
kind: Pod
metadata:
  name: lagopus-server
  labels:
    lagopustype: external
spec:
  containers:
  - name: lagopus-server
    image: qlyoung/lagopus-server
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
      - name: nfsvol
        mountPath: "/lagopus"
  volumes:
  - name: nfsvol
    persistentVolumeClaim:
      claimName: jobdata-pvc
  imagePullSecrets:
  - name: regcred
