apiVersion: v1
kind: Pod
metadata:
  name: lagopus-server
  labels:
    lagopustype: external
spec:
  containers:
  - name: lagopus-server
    image: qlyoung/lagopus-server
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
      - name: nfsvol
        mountPath: "/lagopus"
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: lagopus12345
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: nfsvol
      mountPath: /var/lib/mysql
      subPath: database
  volumes:
  - name: nfsvol
    persistentVolumeClaim:
      claimName: lagopus-pvc
  imagePullSecrets:
  - name: regcred
